This is makeindex, version 2.17 [TeX Live 2023] (kpathsea + Thai support).
Scanning style file ./dissertation.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file dissertation.acn....done (129 entries accepted, 0 rejected).
Sorting entries....done (962 comparisons).
Generating output file dissertation.acr....done (62 lines written, 0 warnings).
Output written in dissertation.acr.
Transcript written in dissertation.alg.
