This is makeindex, version 2.17 [TeX Live 2026/dev] (kpathsea + Thai support).
Scanning style file ./dissertation.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file dissertation.acn....done (127 entries accepted, 0 rejected).
Sorting entries....done (913 comparisons).
Generating output file dissertation.acr....done (56 lines written, 0 warnings).
Output written in dissertation.acr.
Transcript written in dissertation.alg.
